from fdfgen import forge_fdf
import os

# TODO: Include weapon stuff

fields = [('ClassLevel','Hello'),
          ('Background','Hello2'),
          ('PlayerName','Hello3'),
          ('CharacterName','Hello4'),
          ('Race','Hello5'),
          ('Alignment','Hello6'),
          ('XP','Hello7'),
          ('Inspiration','Hello8'),
          ('STR','Hello9'),
          ('ProfBonus','Hello10'),
          ('AC','Hello11'),
          ('Initiative','Hello12'),
          ('Speed','Hello13'),
          ('PersonalityTraits','Hello14'),
          ('STRmod','Leslie'),
          ('HPMax','Ben'),
          ('ST Strength','Ron'),
          ('DEX','Ann'),
          ('HPCurrent','Chris'),
          ('Ideals','Andy'),
          ('DEXmod','April'),
          ('HPTemp','Tom'),
          ('Bonds','Jerry'),
          ('CON','Craig'),
          ('HDTotal','Harry'),
          ('CONmod','Ron'),
          ('HD','Hermione'),
          ('Flaws','Dumbledore'),
          ('INT','Draco'),
          ('ST Dexterity','Crabbe'),
          ('ST Constitution','Goyle'),
          ('ST Intelligence','Snape'),
          ('ST Wisdom','Quirrel'),
          ('ST Charisma','Lockhart'),
          ('Acrobatics','Neville'),
          ('Animal','Hagrid'),
          ('Athletics','Lupin'),
          ('Deception','Umbridge'),
          ('History','Trelawney'),
          ('Insight','McGonnagall'),
          ('Intimidation','Voldemort'),
          ('INTmod','Fred'),
          ('Investigation','George'),
          ('WIS','Ginny'),
          ('Arcana','Arthur'),
          ('Perception','Molly'),
          ('WISmod','Bill'),
          ('CHA','Percy'),
          ('Nature','Vernon'),
          ('Performace','Petunia'),
          ('Medicine','Lily'),
          ('Religion','Sirius'),
          ('Stealth','Peter Pettigrew'),
          ('Persuasion','Seamus'),
          ('SleightofHand','Dean'),
          ('CHamod','Blaise'),
          ('Survival','Lucius'),
          ('AttacksSpellcasting','Narcissa'),
          ('Passive','Bellatrix'),
          ('CP','Gryffindor'),
          ('ProficienciesLang','Ravenclaw'),
          ('SP','Hufflepuff'),
          ('EP','Slytherin'),
          ('GP','Hogwarts'),
          ('PP','Heh, PP'),
          ('Equipment','Five'),
          ('Features and Traits','Four'),
          ('CharacterName 2','Three'),
          ('Age','Two'),
          ('Height','One'),
          ('Weight','Blast off'),
          ('Eyes','Yes, please'),
          ('Skin','No thanks'),
          ('Allies','Axis'),
          ('FactionName','Our Cabinet\'s fractured into factions.'),
          ('Backstory','THE WHOLE FUCKING POINT OF THIS THING!!!!!!1111!!11!!11'),
          ('Feat+Traits','Hands'),
          ]
fdf = forge_fdf("", fields, [], [], [])
fdf_file = open("char_sheet.fdf", "w")
fdf_file.write(fdf)
fdf_file.close()
os.system("pdftk CharacterSheet_3Pgs_\ Complete.pdf fill_form char_sheet.fdf output char_sheet.pdf")
